const invModel = require("../models/inventory-model")
const utilities = require("../utilities/")

const invCont = {}

/* ***************************
 *  Build inventory by classification view
 * ************************** */
invCont.buildByClassificationId = async function (req, res, next) {
  const classification_id = req.params.classificationId;
  const data = await invModel.getInventoryByClassificationId(classification_id);
  const grid = await utilities.buildClassificationGrid(data);
  let nav = await utilities.getNav();
  const className = data[0].classification_name;
  res.render("./inventory/classification", {
    title: className + " vehicles",
    nav,
    grid,
  });
};

/* ***************************
 *  Build specific inventory item detail view
 * ************************** */
invCont.getVehicleDetail = async function (req, res, next) {
  const inventoryId = req.params.inventoryId;
  const vehicleData = await invModel.getVehicleById(inventoryId);
  const vehicleDetail = utilities.buildVehicleDetailHTML(vehicleData);
  let nav = await utilities.getNav();

  res.render("inventory/detail", {
    title: vehicleDetail.title, // Dynamic title from the utility function
    nav,
    content: vehicleDetail.html, // The HTML content generated by the utility
  });
};

module.exports = invCont